const API_URL = "https://script.google.com/macros/s/AKfycbxKYY6K2KjieKJh021nKYspMKgZH4lcMC5I3OEynZWR13OsZmWzTJmMr_EUQhY7cYE/exec";
const PASSWORD = "0418";
const ANNIVERSARY = "2024-04-18";
const $ = id => document.getElementById(id);
let state = {letters:[], songs:[], todos:[], memories:[], current:'home', month:new Date(), selectedMood:'😀', letterPhoto:'', memoryPhoto:''};
const fmt = v => { const d = new Date(v); return Number.isNaN(d) ? (v||'') : d.toLocaleString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}); };
const dateKey = v => { const d=new Date(v); if(Number.isNaN(d)) return ''; return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const esc = s => String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function show(screen){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(screen).classList.add('active');state.current=screen;document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen));const titles={home:['교환일기','오늘도 기록하기'],letters:['편지','우리의 마음'],write:['새 편지 쓰기','사진과 오노추도 함께'],calendar:['캘린더','날짜별 기록'],songs:['오노추','오늘의 노래 추천'],week:['이번주','함께 하고 싶은 것'],memories:['추억','사진 모아보기'],capsule:['타임캡슐','정해진 날에 열리는 편지'],settings:['설정','앱 관리']};$('screenTitle').textContent=titles[screen][0];$('screenSub').textContent=titles[screen][1];}
document.addEventListener('click',e=>{const t=e.target.closest('[data-screen]'); if(t) show(t.dataset.screen);});
$('loginBtn').onclick=()=>{ if($('password').value===PASSWORD){$('login').classList.add('hidden');$('app').classList.remove('hidden');init();} else $('loginStatus').textContent='비밀번호가 달라요.' };
$('password').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
function setToday(){const d=new Date();$('todayText').textContent=d.toLocaleDateString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',weekday:'long'});const a=new Date(ANNIVERSARY);const diff=Math.floor((d-a)/86400000)+1;$('ddayText').textContent=`D+${diff}`;}
async function api(payload){const res=await fetch(API_URL,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});return res.json();}
async function loadAll(){try{const res=await fetch(API_URL);const data=await res.json();state.letters=data.letters||[];state.songs=data.songs||[];state.todos=data.todos||[];state.memories=data.memories||[];}catch(e){console.log(e)} renderAll();}
function renderAll(){renderLetters();renderCalendar();renderSongs();renderTodos();renderMemories();renderCapsules();renderHomeTodo();}
function renderLetters(filter='all'){const box=$('letterList');let list=[...state.letters].reverse().filter(x=>!x.openDate || new Date(x.openDate)<=new Date());if(filter!=='all')list=list.filter(x=>x.writer===filter);box.innerHTML=list.length?'':'<div class="item"><div class="meta">아직 편지가 없어요.</div></div>';list.forEach(l=>{box.insertAdjacentHTML('beforeend',`<div class="item row-card" onclick="openLetter(${l.row})"><div class="grow"><div class="item-title">${esc(l.title)}</div><div class="meta">${esc(l.writer)} · ${fmt(l.date)} ${l.mood?`· ${esc(l.mood)}`:''}</div><div class="likes">💙 ${l.likes||0}　💬 ${(l.comments||[]).length}</div></div>${l.photoUrl?`<img class="thumb" src="${l.photoUrl}">`:''}</div>`)});}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLetters(b.dataset.filter)});
function openLetter(row){const l=state.letters.find(x=>x.row==row);if(!l)return; if(l.openDate && new Date(l.openDate)>new Date()){const days=Math.ceil((new Date(l.openDate)-new Date())/86400000);detailContent.innerHTML=`<h3>🔒 ${esc(l.title)}</h3><p class="meta">아직 열 수 없어요. D-${days}</p>`;detailDialog.showModal();return;}detailContent.innerHTML=`<h3>${esc(l.title)}</h3><p class="meta">${esc(l.writer)} · ${fmt(l.date)}</p>${l.photoUrl?`<img class="preview" src="${l.photoUrl}">`:''}<p style="white-space:pre-wrap;line-height:1.7">${esc(l.content)}</p>${songCard(l.songUrl)}<div class="likes"><button onclick="likeLetter(${l.row})">💙 좋아요 ${l.likes||0}</button><span>💬 댓글 ${(l.comments||[]).length}</span></div><div id="comments">${(l.comments||[]).map(c=>`<div class="meta">${esc(c.writer)}: ${esc(c.text)}</div>`).join('')}</div><div class="inline-form"><input id="commentText" placeholder="댓글"><button onclick="addComment(${l.row})">전송</button></div>`;detailDialog.showModal();}
async function likeLetter(row){await api({type:'letter-like',row});await loadAll();openLetter(row)}
async function addComment(row){const text=$('commentText').value.trim();if(!text)return;await api({type:'letter-comment',row,writer:'예은',text});await loadAll();openLetter(row)}
function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$('pickLetterPhoto').onclick=()=>$('letterPhotoFile').click();$('letterPhotoFile').onchange=async()=>{const f=$('letterPhotoFile').files[0];if(!f)return;state.letterPhoto=await fileToData(f);$('letterPhotoPreview').src=state.letterPhoto;$('letterPhotoPreview').classList.remove('hidden')};
$('moods').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.selectedMood=b.dataset.mood;document.querySelectorAll('.moods button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};
$('isCapsule').onchange=e=>$('capsuleDateWrap').classList.toggle('hidden',!e.target.checked);
$('letterSong').addEventListener('input',()=>{$('letterSongPreview').innerHTML=songCard($('letterSong').value.trim())});
$('saveLetterBtn').onclick=async()=>{const title=$('letterTitle').value.trim(),content=$('letterContent').value.trim();if(!title||!content){$('letterStatus').textContent='제목과 내용을 적어주세요.';return}await api({type:'letter-add',writer:$('writer').value,mood:state.selectedMood,title,content,photoUrl:state.letterPhoto,songUrl:$('letterSong').value.trim(),openDate:$('isCapsule').checked?$('capsuleDate').value:''});$('letterTitle').value='';$('letterContent').value='';$('letterSong').value='';state.letterPhoto='';$('letterPhotoPreview').classList.add('hidden');$('letterStatus').textContent='저장 완료';await loadAll();show('letters')};
function songCard(url){if(!url)return '';const id=(url.match(/(?:v=|youtu\.be\/|shorts\/)([\w-]+)/)||[])[1];const img=id?`https://img.youtube.com/vi/${id}/hqdefault.jpg`:'';return `<div class="song-card">${img?`<img src="${img}">`:''}<div><b>오노추</b><p class="meta">유튜브 링크</p><a href="${esc(url)}" target="_blank">▶ 듣기</a></div></div>`}
$('addSong').onclick=async()=>{const url=$('songLink').value.trim();if(!url)return;await api({type:'song-add',url});$('songLink').value='';await loadAll()};
function renderSongs(){const box=$('songList');box.innerHTML='';[...state.songs].reverse().forEach(s=>box.insertAdjacentHTML('beforeend',songCard(s.url)))}
$('addTodo').onclick=async()=>{const text=$('todoText').value.trim();if(!text)return;await api({type:'todo-add',text,writer:'예은'});$('todoText').value='';await loadAll()};
function renderTodos(){const box=$('todoList');box.innerHTML='';state.todos.forEach(t=>box.insertAdjacentHTML('beforeend',`<div class="item todo-row ${t.done?'done':''}" onclick="toggleTodo('${t.id}')"><div class="todo-left"><span class="check">${t.done?'✓':''}</span><b>${esc(t.text)}</b></div></div>`))}
function renderHomeTodo(){const box=$('homeTodo');const todos=state.todos.slice(0,4);box.innerHTML=todos.map(t=>`<div class="meta">${t.done?'☑':'☐'} ${esc(t.text)}</div>`).join('')||'<div class="meta">이번주 할 일을 추가해요.</div>'}
async function toggleTodo(id){await api({type:'todo-toggle',id});await loadAll()}
$('pickMemory').onclick=()=>$('memoryFile').click();$('memoryFile').onchange=async()=>{const f=$('memoryFile').files[0];if(!f)return;state.memoryPhoto=await fileToData(f);$('memoryPreview').src=state.memoryPhoto;$('memoryPreview').classList.remove('hidden')};
$('saveMemory').onclick=async()=>{if(!state.memoryPhoto)return;await api({type:'memory-add',title:$('memoryTitle').value.trim(),memo:$('memoryMemo').value.trim(),url:state.memoryPhoto});$('memoryTitle').value='';$('memoryMemo').value='';state.memoryPhoto='';$('memoryPreview').classList.add('hidden');await loadAll()};
function renderMemories(){const box=$('memoryList');box.innerHTML='';[...state.memories].reverse().forEach(m=>box.insertAdjacentHTML('beforeend',`<div class="memory-card"><img src="${m.url}"><div><b>${esc(m.title||'추억')}</b><p class="meta">${fmt(m.date)}</p></div></div>`))}
function renderCapsules(){const box=$('capsuleList');const list=state.letters.filter(x=>x.openDate);box.innerHTML=list.length?'':'<div class="item"><div class="meta">아직 타임캡슐이 없어요.</div></div>';list.reverse().forEach(c=>{const open=new Date(c.openDate)<=new Date();const days=Math.ceil((new Date(c.openDate)-new Date())/86400000);box.insertAdjacentHTML('beforeend',`<div class="item" onclick="openLetter(${c.row})"><div class="item-title">${open?'🔓':'🔒'} ${esc(c.title)}</div><div class="meta">${c.openDate} ${open?'열렸어요':`D-${days}`}</div></div>`)})}
function renderCalendar(){const d=new Date(state.month.getFullYear(),state.month.getMonth(),1);$('monthLabel').textContent=`${d.getFullYear()}년 ${d.getMonth()+1}월`;const start=d.getDay();const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();let html='';for(let i=0;i<start;i++)html+='<button class="day dim"></button>';const today=dateKey(new Date());for(let n=1;n<=last;n++){const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;const marks=[];if(state.letters.some(x=>dateKey(x.date)===key))marks.push('✉');if(state.memories.some(x=>dateKey(x.date)===key))marks.push('▧');if(state.songs.some(x=>dateKey(x.date)===key))marks.push('♫');if(state.letters.some(x=>x.openDate===key))marks.push('🔒');html+=`<button class="day ${key===today?'today':''}" onclick="showDay('${key}')"><div>${n}</div><div class="marks">${marks.join('')}</div></button>`}$('calendarGrid').innerHTML=html;}
$('prevMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};
function showDay(key){const l=state.letters.filter(x=>dateKey(x.date)===key).length,m=state.memories.filter(x=>dateKey(x.date)===key).length,s=state.songs.filter(x=>dateKey(x.date)===key).length,c=state.letters.filter(x=>x.openDate===key).length;$('dayDetail').innerHTML=`<b>${key}</b><br><br>✉ 편지 ${l}개<br>▧ 추억 ${m}개<br>♫ 오노추 ${s}개<br>🔒 타임캡슐 ${c}개`}
function init(){setToday();loadAll();if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});} 
